[k8s_manager]
k8s-manager ansible_connection=local

[turing_workers]
turing-node01 ansible_host=192.168.8.191
turing-node02 ansible_host=192.168.8.111
turing-node03 ansible_host=192.168.8.128
turing-node04 ansible_host=192.168.8.203
turing-node05 ansible_host=192.168.8.144
turing-node06 ansible_host=192.168.8.228
turing-node07 ansible_host=192.168.8.194

[turing_registry]
turing-node01

[turing_workers:vars]
ansible_python_interpreter=/usr/bin/python3.13