apiVersion: apps/v1
kind: Deployment

metadata:
  name: hello-k8s

spec:
  replicas: 2

  selector:
    matchLabels:
      app: hello-k8s

  template:
    metadata:
      labels:
        app: hello-k8s

    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          ports:
            - containerPort: 80