---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: visitor-counter
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: visitor-counter
  template:
    metadata:
      labels:
        app: visitor-counter
    spec:
      containers:
        - name: visitor-counter
          image: 192.168.8.191:5000/visitor-counter:2.2
          ports:
            - containerPort: 5000
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 250m
              memory: 128Mi

---
apiVersion: v1
kind: Service
metadata:
  name: visitor-counter
  namespace: default
spec:
  type: NodePort
  selector:
    app: visitor-counter
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30500
