---
apiVersion: apps/v1
kind: Deployment

metadata:
  name: configmap-nginx

spec:
  replicas: 1

  selector:
    matchLabels:
      app: configmap-nginx

  template:
    metadata:
      labels:
        app: configmap-nginx

    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          ports:
            - containerPort: 80

          volumeMounts:
            - name: html-volume
              mountPath: /usr/share/nginx/html
              readOnly: true

      volumes:
        - name: html-volume
          configMap:
            name: nginx-html